baseurl = "https://coding-club-linz.github.io/my-informatics-world-2020/"
languageCode = "de-at"
title = "My Informatics World 2020"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Global Azure Bootcamp 2020 Linz"
	description = "All around the world user groups and communities will come together from April 23 - April 25, 2020 once again in the seventh Global Azure Bootcamp event. Join us on Friday, April 24, 2020 in Linz."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "My Informatics World 2020"

		[params.navigation.links]
			about     = "Über uns"
            appointments   = "Termine"
			partners   = "Projektpartner"
            sponsors   = "Sponsoren"
			contact   = "Kontakt"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Global Azure Bootcamp 2020"
		subtitle   = "Friday, April 24, 2020 - Hollywood Megaplex Pasching"
		buttonText = "Find out more"

	# Sessions section
	[params.sessions]
		headline    = "Sessions"
		
		[[params.sessions.list]]
            icon = "fa-diamond"
            title = "Sturdy Templates"
	        description = "Our templates are updated regularly so they don't break."

	# Contact section
	[params.contact]
		twitter = "coderdojolinz"
		email = "info@myinformaticsworld.org"

	# Google Maps section
	[params.location]
	 	latitude  = "48.2443694"
	 	longitude = "14.2349452"
	 	maps_api_key = ""
